name = "analytics-durable-object-dev"
main = "./src/index.mjs"
compatibility_date = "2023-06-19"

[durable_objects]
bindings = [{name = "ANALYTICS_DATA", class_name = "Data"}]

[[migrations]]
tag = "v1" 
new_classes = ["Data"]

[vars]
DO_NAME = "data" # string used to create the id of the DO using .idFromName()
